version: '3'

services: 
    jwt-auth-api:
        build: 
            context: .
        ports: 
            - '8000:8000'
        volumes: 
            - ./src:/src
        command: >
            sh -c 'python manage.py test --settings=jwt_auth.settings.prods && flake8 &&
                   python manage.py migrate --settings=jwt_auth.settings.prods &&
                   python manage.py wait_for_db --settings=jwt_auth.settings.prods &&
                   python manage.py runserver 0.0.0.0:8000 --settings=jwt_auth.settings.prods'
        environment: 
            - DB_HOST=db
            - DB_NAME=app1
            - DB_USER=postgres
            - DB_PASS=secret
        depends_on:
            - db

    db:
        image: postgres:10-alpine
        environment: 
            - POSTGRES_DB=app1
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
