version: '3'

services: 
    jwt-auth-api:
        build: 
            context: .
        expose: 
            - '8000'
        volumes: 
            - ./src:/src
            - static_volume:/vol/web/static
            - media_volume:/vol/web/media
        command: >
            sh -c 'python manage.py test --settings=jwt_auth.settings.prods && flake8 &&
                   python manage.py migrate --settings=jwt_auth.settings.prods &&
                   python manage.py wait_for_db --settings=jwt_auth.settings.prods &&
                   gunicorn --env DJANGO_SETTINGS_MODULE=jwt_auth.settings.prods jwt_auth.wsgi:application --bind 0.0.0.0:8000'
        environment: 
            - DB_HOST=db
            - DB_NAME=app1
            - DB_USER=postgres
            - DB_PASS=secret
        depends_on:
            - db

    db:
        image: postgres:10-alpine
        environment: 
            - POSTGRES_DB=app1
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret

    nginx:
        build: ./nginx
        volumes: 
            - static_volume:/vol/web/static
            - media_volume:/vol/web/media
        ports: 
            - '80:80'
        depends_on: 
            - jwt-auth-api

volumes: 
    static_volume:
    media_volume:
